run:
  timeout: 5m
output:
  uniq-by-line: false
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
  # allow dot-importing ginkgo and gomega
  - linters: [golint, stylecheck]
    source: '\. "github\.com/onsi/(gomega|ginkgo)"'
    text: "should not use dot imports"
linters:
  enable:
  - gofmt
  - golint
  - goimports
  - stylecheck
linters-settings:
  goimports:
    local-prefixes: github.com/naumvd95/k8s-node-backdoor
