---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-backdoor-daemon
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node-backdoor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node-backdoor
    spec:
      volumes:
        - name: host-ssh
          hostPath:
            path: /home/ubuntu/.ssh
        - name: host-log-input
          hostPath:
            path: /var/log
        - name: host-log-output
          hostPath:
            path: /home/ubuntu/admin-backdoor
      containers:
        - name: node-backdoor
          image: vnaumov/k8s-node-backdoor:latest
          imagePullPolicy: Always
          env:
            - name: AUTHORIZED_KEYS_PATH
              value: "/ssh-output/authorized_keys"
            - name: LOGS_INPUT_PATH
              value: "/logs-input"
            - name: LOGS_OUTPUT_PATH
              value: "/logs-output"
          volumeMounts:
            - name: host-ssh
              mountPath: /ssh-output
            - name: host-log-input
              mountPath: /logs-input
            - name: host-log-output
              mountPath: /logs-output
