---
- name: Install apt-transport-https
  apt:
    name: "apt-transport-https"
    state: present
    update_cache: yes

- name: Add Docker APT GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    state: present
    filename: 'docker'

- name: Install docker engine (Debian/Ubuntu)
  apt:
    update_cache: yes
    name: "docker-ce={{ docker_version }}*"
    state: present

- name: Hold docker version
  dpkg_selections:
    name: docker-ce
    selection: hold

- name: Copy Docker daemon configuration file
  template:
    src: "daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0755

- name: Enable and check Docker service
  systemd:
    name: docker
    daemon_reload: yes
    state: started
    enabled: yes
  register: started_docker
