#TODO Application
apply_daemon: true
daemonset_path: path/to/daemonset/template


# Kubeadm
cluster_name:
master_ip: "{{ hostvars[groups['k8s-boilerplate-masters'][0]]['ansible_default_ipv4'].address }}"
kubeadm_token: 783bde.3f89s0fje9f38fhf
kubeadmin_config: /etc/kubernetes/admin.conf
kubeadm_dir: /root/kubeadm_configuration

# CNI
network_dir: k8s-network-templates
pod_network_cidr: "192.168.0.0/16"
service_cidr: "10.100.0.0/16"

# CRI
docker_version: "17.03"
docker_bip: "172.17.0.0/16"
