---

- name: reset kubeadm
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Create kubeadm config directory
  file:
    path: "{{ kubeadm_dir }}"
    state: directory

- name: "Copy kubeadm config"
  template:
    src: kubeadm-worker.yaml.j2
    dest: "{{ kubeadm_dir }}/kubeadm-worker.yaml"

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join  --config {{ kubeadm_dir }}/kubeadm-worker.yaml
  register: join_cluster
  notify:
    - recreate kube-dns
    - restart kubelet
