---

- name: reset kubeadm
  shell: "kubeadm reset --force"
  register: reset_cluster

- name: Join to Kubernetes cluster
  when: reset_cluster is succeeded
  shell: |
    kubeadm join --token {{ kubeadm_token }} \
                --discovery-token-unsafe-skip-ca-verification \
                {{ master_internal_ip }}:6443
  register: join_cluster
  notify:
    - recreate kube-dns
    - restart kubelet
