name: Test docker image with go binary

on:
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint
      run: make dockerized-lint
          
    - name: Build binary and pack inside docker image
      run: |
        docker run --rm \
        -v /var/run/docker.sock:/var/run/docker.sock \
        -v $(pwd):/go/src/github.com/naumvd95/k8s-node-backdoor \
        -w=/go/src/github.com/naumvd95/k8s-node-backdoor \
        vnaumov/go-infra-ops:latest make nodebackdoor-image
    
    - name: Get image name
      run: echo "::set-output name=docker_image::$(make nodebackdoor-image-name)"
      id: release_candidate
      
    - name: Smoke test
      run: docker run --rm ${{steps.release_candidate.outputs.docker_image}} daemon --help
